// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: zero

#include "ui.h"

__attribute__((weak)) void switch_left(lv_event_t * e)
{
	// Your code here
}

__attribute__((weak)) void switch_right(lv_event_t * e)
{
	// Your code here
}

__attribute__((weak)) void app_launch(lv_event_t * e)
{
	// Your code here
}

__attribute__((weak)) void go_back_home(lv_event_t * e)
{
	// Your code here
}

__attribute__((weak)) void app_install(lv_event_t * e)
{
	// Your code here
}

__attribute__((weak)) void app_remove(lv_event_t * e)
{
	// Your code here
}

__attribute__((weak)) void app_update(lv_event_t * e)
{
	// Your code here
}

__attribute__((weak)) void go_back_app_store(lv_event_t * e)
{
	// Your code here
}

__attribute__((weak)) void main_key_switch(lv_event_t * e)
{
	// Your code here
}

__attribute__((weak)) void app_store_switch(lv_event_t * e)
{
	// Your code here
}

__attribute__((weak)) void app_note_switch(lv_event_t * e)
{
	// Your code here
}

__attribute__((weak)) void python_console_input(lv_event_t * e)
{
	// Your code here
}
